url: "https://atticadt.uwmh.eu"
baseurl: "/v2"
title: "Impetus Attica Digital Twins"

plugins:
  - jekyll-minifier

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_spaces_around_tags: true
  remove_spaces_between_tags: true
  css_minification: true
  js_minification: true

compress_html:
  comments: all

collections:
  innovations:
    output: false
  dashboards:
    plant_nursery:
      output: false
    plant_nursery_dashboard:
      output: false
    farmair:
      output: false
    kokotou0:
      output: false
