url: "https://beta.atticadt.uwmh.eu"
baseurl: "/"
title: "Impetus Attica Digital Twins"

compress_html:
  comments: all

collections:
  innovations:
    output: false
  dashboards:
    plant_nursery:
      output: false
    plant_nursery_dashboard:
      output: false
    farmair:
      output: false
    kokotou0:
      output: false
